Insert into cidade (idCidade, nome, uf) values (1,'Porto Velho', 'RO');
Insert into cidade (idCidade, nome, uf) values (2,'Presidente Médici', 'RO');
Insert into cidade (idCidade, nome, uf) values (3,'Rio Crespo', 'RO');
Insert into cidade (idCidade, nome, uf) values (4,'Rolim de Moura', 'RO');
Insert into cidade (idCidade, nome, uf) values (5,'Santa Luzia D''Oeste', 'RO');
Insert into cidade (idCidade, nome, uf) values (6,'Vilhena', 'RO');
Insert into cidade (idCidade, nome, uf) values (7,'São Miguel do Guaporé', 'RO');
Insert into cidade (idCidade, nome, uf) values (8,'Nova Mamoré', 'RO');
Insert into cidade (idCidade, nome, uf) values (9,'Alvorada D''Oeste', 'RO');
Insert into cidade (idCidade, nome, uf) values (10,'Porto Walter', 'AC');
Insert into cidade (idCidade, nome, uf) values (11,'Rio Branco', 'AC');
Insert into cidade (idCidade, nome, uf) values (12,'Rodrigues Alves', 'AC');
Insert into cidade (idCidade, nome, uf) values (13,'Santa Rosa do Purus', 'AC');
Insert into cidade (idCidade, nome, uf) values (14,'Senador Guiomard', 'AC');
Insert into cidade (idCidade, nome, uf) values (15,'Sena Madureira', 'AC');
Insert into cidade (idCidade, nome, uf) values (16,'Tarauacá', 'AC');
Insert into cidade (idCidade, nome, uf) values (17,'Manacapuru', 'AM');
Insert into cidade (idCidade, nome, uf) values (18,'Manaquiri', 'AM');
Insert into cidade (idCidade, nome, uf) values (19,'Manaus', 'AM');
Insert into cidade (idCidade, nome, uf) values (20,'Manicoré', 'AM');
Insert into cidade (idCidade, nome, uf) values (21,'Maraã', 'AM');
Insert into cidade (idCidade, nome, uf) values (22,'Maués', 'AM');
Insert into cidade (idCidade, nome, uf) values (23,'Nhamundá', 'AM');
Insert into cidade (idCidade, nome, uf) values (24,'Boa Vista', 'RR');
Insert into cidade (idCidade, nome, uf) values (25,'Bonfim', 'RR');
Insert into cidade (idCidade, nome, uf) values (26,'Cantá', 'RR');
Insert into cidade (idCidade, nome, uf) values (27,'Caracaraí', 'RR');
Insert into cidade (idCidade, nome, uf) values (28,'Caroebe', 'RR');
Insert into cidade (idCidade, nome, uf) values (29,'Iracema', 'RR');
Insert into cidade (idCidade, nome, uf) values (30,'Mucajaí', 'RR');
Insert into cidade (idCidade, nome, uf) values (31,'Barcarena', 'PA');
Insert into cidade (idCidade, nome, uf) values (32,'Belém', 'PA');
Insert into cidade (idCidade, nome, uf) values (33,'Belterra', 'PA');
Insert into cidade (idCidade, nome, uf) values (34,'Benevides', 'PA');
Insert into cidade (idCidade, nome, uf) values (35,'Macapá', 'AP');
Insert into cidade (idCidade, nome, uf) values (36,'Mazagão', 'AP');
Insert into cidade (idCidade, nome, uf) values (37,'Oiapoque', 'AP');
Insert into cidade (idCidade, nome, uf) values (38,'Palmas', 'TO');
Insert into cidade (idCidade, nome, uf) values (39,'Tocantínia', 'TO');
Insert into cidade (idCidade, nome, uf) values (40,'Tocantinópolis', 'TO');
Insert into cidade (idCidade, nome, uf) values (41,'Tupirama', 'TO');
Insert into cidade (idCidade, nome, uf) values (42,'Tupiratins', 'TO');
Insert into cidade (idCidade, nome, uf) values (43,'São Luís', 'MA');
Insert into cidade (idCidade, nome, uf) values (44,'São Luís Gonzaga do Maranhão', 'MA');
Insert into cidade (idCidade, nome, uf) values (45,'São Mateus do Maranhão', 'MA');
Insert into cidade (idCidade, nome, uf) values (46,'São Pedro da Água Branca', 'MA');
Insert into cidade (idCidade, nome, uf) values (47,'São Pedro dos Crentes', 'MA');
Insert into cidade (idCidade, nome, uf) values (48,'Socorro do Piauí', 'PI');
Insert into cidade (idCidade, nome, uf) values (49,'Sussuapara', 'PI');
Insert into cidade (idCidade, nome, uf) values (50,'Tamboril do Piauí', 'PI');
Insert into cidade (idCidade, nome, uf) values (51,'Tanque do Piauí', 'PI');
Insert into cidade (idCidade, nome, uf) values (52,'Teresina', 'PI');
Insert into cidade (idCidade, nome, uf) values (53,'União', 'PI');
Insert into cidade (idCidade, nome, uf) values (54,'Eusébio', 'CE');
Insert into cidade (idCidade, nome, uf) values (55,'Farias Brito', 'CE');
Insert into cidade (idCidade, nome, uf) values (56,'Forquilha', 'CE');
Insert into cidade (idCidade, nome, uf) values (57,'Fortaleza', 'CE');
Insert into cidade (idCidade, nome, uf) values (58,'Mossoró', 'RN');
Insert into cidade (idCidade, nome, uf) values (59,'Natal', 'RN');
Insert into cidade (idCidade, nome, uf) values (60,'Nísia Floresta', 'RN');
Insert into cidade (idCidade, nome, uf) values (61,'Nova Cruz', 'RN');
Insert into cidade (idCidade, nome, uf) values (62,'Jericó', 'PB');
Insert into cidade (idCidade, nome, uf) values (63,'João Pessoa', 'PB');
Insert into cidade (idCidade, nome, uf) values (64,'Juarez Távora', 'PB');
Insert into cidade (idCidade, nome, uf) values (65,'Juazeirinho', 'PB');
Insert into cidade (idCidade, nome, uf) values (66,'Junco do Seridó', 'PB');
Insert into cidade (idCidade, nome, uf) values (67,'Quixaba', 'PE');
Insert into cidade (idCidade, nome, uf) values (68,'Recife', 'PE');
Insert into cidade (idCidade, nome, uf) values (69,'Riacho das Almas', 'PE');
Insert into cidade (idCidade, nome, uf) values (70,'São Lourenço da Serra', 'SP');
Insert into cidade (idCidade, nome, uf) values (71,'São Luís do Paraitinga', 'SP');
Insert into cidade (idCidade, nome, uf) values (72,'São Manuel', 'SP');
Insert into cidade (idCidade, nome, uf) values (73,'São Miguel Arcanjo', 'SP');
Insert into cidade (idCidade, nome, uf) values (74,'São Paulo', 'SP');
Insert into cidade (idCidade, nome, uf) values (75,'São Pedro', 'SP');
Insert into cidade (idCidade, nome, uf) values (76,'Rio das Flores', 'RJ');
Insert into cidade (idCidade, nome, uf) values (77,'Rio das Ostras', 'RJ');
Insert into cidade (idCidade, nome, uf) values (78,'Rio de Janeiro', 'RJ');
Insert into cidade (idCidade, nome, uf) values (79,'Santa Maria Madalena', 'RJ');
Insert into cidade (idCidade, nome, uf) values (80,'Brasília', 'DF');
Insert into cidade (idCidade, nome, uf) values (81,'Goianésia', 'GO');
Insert into cidade (idCidade, nome, uf) values (82,'Goiânia', 'GO');
Insert into cidade (idCidade, nome, uf) values (83,'Goianira', 'GO');
Insert into cidade (idCidade, nome, uf) values (84,'Goiás', 'GO');

