Insert into estado (uf, nome) values ('AC', 'Acre');
Insert into estado (uf, nome) values ('AL', 'Alagoas');
Insert into estado (uf, nome) values ('AP', 'Amapá');
Insert into estado (uf, nome) values ('AM', 'Amazonas');
Insert into estado (uf, nome) values ('BA', 'Bahia');
Insert into estado (uf, nome) values ('CE', 'Ceará');
Insert into estado (uf, nome) values ('DF', 'Distrito Federal');
Insert into estado (uf, nome) values ('ES', 'Espírito Santo');
Insert into estado (uf, nome) values ('GO', 'Goiás');
Insert into estado (uf, nome) values ('MA', 'Maranhão');
Insert into estado (uf, nome) values ('MT', 'Mato Grosso');
Insert into estado (uf, nome) values ('MS', 'Mato Grosso do Sul');
Insert into estado (uf, nome) values ('MG', 'Minas Gerais');
Insert into estado (uf, nome) values ('PA', 'Pará');
Insert into estado (uf, nome) values ('PB', 'Paraíba');
Insert into estado (uf, nome) values ('PR', 'Paraná');
Insert into estado (uf, nome) values ('PE', 'Pernambuco');
Insert into estado (uf, nome) values ('PI', 'Piauí');
Insert into estado (uf, nome) values ('RJ', 'Rio de Janeiro');
Insert into estado (uf, nome) values ('RN', 'Rio Grande do Norte');
Insert into estado (uf, nome) values ('RS', 'Rio Grande do Sul');
Insert into estado (uf, nome) values ('RO', 'Rondônia');
Insert into estado (uf, nome) values ('RR', 'Roraima');
Insert into estado (uf, nome) values ('SC', 'Santa Catarina');
Insert into estado (uf, nome) values ('SP', 'São Paulo');
Insert into estado (uf, nome) values ('SE', 'Sergipe');
Insert into estado (uf, nome) values ('TO', 'Tocantins');
