INSERT INTO tipo (descricao) values ('motocicleta');
INSERT INTO tipo (descricao) values ('motoneta');
INSERT INTO tipo (descricao) values ('triciclo');
INSERT INTO tipo (descricao) values ('quadriciclo');
INSERT INTO tipo (descricao) values ('automóvel');
INSERT INTO tipo (descricao) values ('microônibus');
INSERT INTO tipo (descricao) values ('ônibus');
INSERT INTO tipo (descricao) values ('reboque');
INSERT INTO tipo (descricao) values ('charrete');
INSERT INTO tipo (descricao) values ('caminhonete');
INSERT INTO tipo (descricao) values ('caminhão');
INSERT INTO tipo (descricao) values ('carroça');
INSERT INTO tipo (descricao) values ('automóvel');
INSERT INTO tipo (descricao) values ('trator de rodas');
INSERT INTO tipo (descricao) values ('trator de esteira');
INSERT INTO tipo (descricao) values ('trator misto');
INSERT INTO tipo (descricao) values ('furgão');